export const weatherBackgroundData = {
  day: {
    "Sunny": "#0ED4FF",
    "Clear": "#82CAFF",
    "Partly cloudy": "#FFD700",
    "Cloudy": "#808080",
    "Overcast": "#A9A9A9",
    "Mist": "#D3D3D3",
    "Patchy rain possible": "#4682B4",
    "Patchy snow possible": "#B0C4DE",
    "Patchy sleet possible": "#87CEEB",
    "Patchy freezing drizzle possible": "#B0E0E6",
    "Thundery outbreaks possible": "#FFA500",
    "Blowing snow": "#FFFFFF",
    "Blizzard": "#FFFFFF",
    "Fog": "#FFA07A",
    "Freezing fog": "#FFE4B5",
    "Patchy light drizzle": "#708090",
    "Light drizzle": "#708090",
    "Freezing drizzle": "#B0E0E6",
    "Heavy freezing drizzle": "#B0E0E6",
    "Patchy light rain": "#4682B4",
    "Light rain": "#4682B4",
    "Moderate rain at times": "#4682B4",
    "Moderate rain": "#4682B4",
    "Heavy rain at times": "#4682B4",
    "Heavy rain": "#4682B4",
    "Light freezing rain": "#B0E0E6",
    "Moderate or heavy freezing rain": "#B0E0E6",
    "Light sleet": "#87CEEB",
    "Moderate or heavy sleet": "#87CEEB",
    "Patchy light snow": "#B0C4DE",
    "Light snow": "#B0C4DE",
    "Patchy moderate snow": "#B0C4DE",
    "Moderate snow": "#B0C4DE",
    "Patchy heavy snow": "#B0C4DE",
    "Heavy snow": "#B0C4DE",
    "Ice pellets": "#ADD8E6",
    "Light rain shower": "#4682B4",
    "Moderate or heavy rain shower": "#4682B4",
    "Torrential rain shower": "#4682B4",
    "Light sleet showers": "#87CEEB",
    "Moderate or heavy sleet showers": "#87CEEB",
    "Light snow showers": "#B0C4DE",
    "Moderate or heavy snow showers": "#B0C4DE",
    "Light showers of ice pellets": "#ADD8E6",
    "Moderate or heavy showers of ice pellets": "#ADD8E6",
    "Patchy light rain with thunder": "#FFA500",
    "Moderate or heavy rain with thunder": "#FFA500",
    "Patchy light snow with thunder": "#B0C4DE",
    "Moderate or heavy snow with thunder": "#B0C4DE"
  },
  night: {
    "Sunny": "#0ED4FF",
    "Clear": "#0c1445",
    "Partly cloudy": "#87CEEB",
    "Cloudy": "#808080",
    "Overcast": "#A9A9A9",
    "Mist": "#D3D3D3",
    "Patchy rain possible": "#4682B4",
    "Patchy snow possible": "#B0C4DE",
    "Patchy sleet possible": "#87CEEB",
    "Patchy freezing drizzle possible": "#B0E0E6",
    "Thundery outbreaks possible": "#FFA500",
    "Blowing snow": "#FFFFFF",
    "Blizzard": "#FFFFFF",
    "Fog": "#FFA07A",
    "Freezing fog": "#FFE4B5",
    "Patchy light drizzle": "#708090",
    "Light drizzle": "#708090",
    "Freezing drizzle": "#B0E0E6",
    "Heavy freezing drizzle": "#B0E0E6",
    "Patchy light rain": "#4682B4",
    "Light rain": "#4682B4",
    "Moderate rain at times": "#4682B4",
    "Moderate rain": "#4682B4",
    "Heavy rain at times": "#4682B4",
    "Heavy rain": "#4682B4",
    "Light freezing rain": "#B0E0E6",
    "Moderate or heavy freezing rain": "#B0E0E6",
    "Light sleet": "#87CEEB",
    "Moderate or heavy sleet": "#87CEEB",
    "Patchy light snow": "#B0C4DE",
    "Light snow": "#B0C4DE",
    "Patchy moderate snow": "#B0C4DE",
    "Moderate snow": "#B0C4DE",
    "Patchy heavy snow": "#B0C4DE",
    "Heavy snow": "#B0C4DE",
    "Ice pellets": "#ADD8E6",
    "Light rain shower": "#4682B4",
    "Moderate or heavy rain shower": "#4682B4",
    "Torrential rain shower": "#4682B4",
    "Light sleet showers": "#87CEEB",
    "Moderate or heavy sleet showers": "#87CEEB",
    "Light snow showers": "#B0C4DE",
    "Moderate or heavy snow showers": "#B0C4DE",
    "Light showers of ice pellets": "#ADD8E6",
    "Moderate or heavy showers of ice pellets": "#ADD8E6",
    "Patchy light rain with thunder": "#FFA500",
    "Moderate or heavy rain with thunder": "#FFA500",
    "Patchy light snow with thunder": "#B0C4DE",
    "Moderate or heavy snow with thunder": "#B0C4DE"
  }
};
